/**
 * Comprehensive Anatomical Structures Dataset
 * Medically verified definitions for 3D Human Anatomy Education
 */

export interface AnatomicalStructure {
  id: string;
  name: string;
  latinName: string;
  system: 'skeletal' | 'muscular' | 'nervous' | 'cardiovascular' | 'respiratory' | 'digestive' | 'urinary' | 'endocrine' | 'lymphatic' | 'reproductive' | 'integumentary' | 'sensory';
  systemName: string;
  category: 'organ' | 'bone' | 'muscle' | 'nerve' | 'vessel' | 'gland' | 'tissue';
  layer: number; // 1: Skin, 2: Subcutaneous, 3: Superficial Muscle, 4: Deep Muscle, 5: Bone, 6: Nervous, 7: Arteries, 8: Veins/Organs
  region: 'head' | 'neck' | 'thorax' | 'abdomen' | 'pelvis' | 'upper_limb' | 'lower_limb' | 'spine';
  regionName: string;
  description: string;
  function: string;
  location: string;
  relatedStructures: string[];
  bloodSupply: string;
  innervation: string;
  histology: string;
  clinicalNotes: string;
  funFact: string;
  position3D: [number, number, number]; // [x, y, z] in Three.js coordinates
  scale3D?: [number, number, number];
  color: string;
  highlightColor?: string;
  image?: string;
}

export const ANATOMY_STRUCTURES: Record<string, AnatomicalStructure> = {
  // --- CARDIOVASCULAR ---
  heart: {
    id: 'heart',
    name: 'Heart',
    latinName: 'Cor Humanum',
    system: 'cardiovascular',
    systemName: 'Cardiovascular System',
    category: 'organ',
    layer: 8,
    region: 'thorax',
    regionName: 'Middle Mediastinum',
    description: 'A four-chambered, hollow muscular organ situated in the thoracic cavity between the lungs, encased in the pericardial sac. It consists of the right atrium, right ventricle, left atrium, and thick-walled left ventricle.',
    function: 'Maintains pulmonary and systemic circulation by rhythmic pumping of deoxygenated blood to the lungs and oxygenated blood to the rest of the body.',
    location: 'Located in the middle mediastinum of the thoracic cavity, posterior to the sternum and costal cartilages, slightly left of the median plane.',
    relatedStructures: ['aorta', 'pulmonary_artery', 'superior_vena_cava', 'inferior_vena_cava', 'coronary_arteries', 'lungs'],
    bloodSupply: 'Right and left coronary arteries arising from aortic sinuses; venous drainage via coronary sinus into the right atrium.',
    innervation: 'Autonomic cardiac plexus: sympathetic (T1-T4, increases rate & contractility) and parasympathetic via vagus nerve (CN X, decreases rate).',
    histology: 'Striated, branching cardiomyocytes joined by intercalated discs containing gap junctions (for synchronous electrical conduction) and desmosomes.',
    clinicalNotes: 'Site of coronary artery disease, myocardial infarction (heart attack), valvular stenosis/regurgitation, and heart failure.',
    funFact: 'The heart beats approximately 100,000 times a day and pumps nearly 7,500 liters (2,000 gallons) of blood through 60,000 miles of blood vessels.',
    position3D: [-0.15, 1.25, 0.2],
    scale3D: [0.38, 0.45, 0.35],
    color: '#dc2626',
    image: '/src/assets/images/realistic_heart_anatomy_1790533416089.jpg'
  },
  aorta: {
    id: 'aorta',
    name: 'Aorta',
    latinName: 'Aorta Thoracica et Abdominalis',
    system: 'cardiovascular',
    systemName: 'Cardiovascular System',
    category: 'vessel',
    layer: 7,
    region: 'thorax',
    regionName: 'Mediastinum & Abdomen',
    description: 'The largest arterial trunk of the human body, arising from the left ventricle. It curves as the aortic arch giving off head and neck branches, then descends through the thorax and abdomen before bifurcating into common iliac arteries.',
    function: 'Conveys oxygenated high-pressure blood from the left ventricle to all systemic organ circulations through elastic recoil (Windkessel effect).',
    location: 'Arises at the aortic valve, arches over pulmonary vessels to T4 level, descends along anterior left vertebral bodies through the diaphragm (T12).',
    relatedStructures: ['heart', 'brachiocephalic_artery', 'carotid_artery', 'subclavian_artery', 'femoral_artery'],
    bloodSupply: 'Vasa vasorum within outer adventitia and outer media.',
    innervation: 'Aortic baroreceptors innervated by the aortic nerve (branch of CN X vagus).',
    histology: 'Elastic artery featuring concentric sheets of fenestrated elastic lamellae with intervening vascular smooth muscle cells in the tunica media.',
    clinicalNotes: 'Susceptible to aortic aneurysm (thoracic/abdominal), acute aortic dissection, coarctation, and atherosclerotic calcification.',
    funFact: 'At peak systolic contraction, the human aorta has a diameter of roughly 2.5 to 3 centimeters—similar in width to an average garden hose.',
    position3D: [-0.05, 1.45, 0.15],
    scale3D: [0.15, 0.8, 0.15],
    color: '#ef4444'
  },
  superior_vena_cava: {
    id: 'superior_vena_cava',
    name: 'Superior Vena Cava',
    latinName: 'Vena Cava Superior',
    system: 'cardiovascular',
    systemName: 'Cardiovascular System',
    category: 'vessel',
    layer: 8,
    region: 'thorax',
    regionName: 'Superior Mediastinum',
    description: 'A large, short valve-less vein that returns deoxygenated blood from the upper half of the body (head, neck, upper limbs, and chest) directly into the right atrium.',
    function: 'Collects systemic venous drainage from head, neck, and arms via brachiocephalic veins and azygos vein to enter the right atrium.',
    location: 'Starts behind the lower border of the first right costal cartilage, descends vertically behind the second and third intercostal spaces to enter the heart.',
    relatedStructures: ['heart', 'jugular_vein', 'subclavian_vein', 'aorta'],
    bloodSupply: 'Receives the azygos vein; nourished by local capillary networks.',
    innervation: 'Perivascular autonomic plexus.',
    histology: 'Large conduit vein with thin tunica media and thick longitudinal collagenous tunica adventitia.',
    clinicalNotes: 'Obstruction by mediastinal tumors (e.g. lung bronchogenic carcinoma or lymphoma) causes SVC syndrome with facial plethora and venous engorgement.',
    funFact: 'Unlike many peripheral limb veins that possess valves to fight gravity, the superior vena cava has no valves because downward blood flow is gravity-assisted.',
    position3D: [0.12, 1.45, 0.18],
    scale3D: [0.12, 0.5, 0.12],
    color: '#3b82f6'
  },

  // --- RESPIRATORY ---
  lungs: {
    id: 'lungs',
    name: 'Lungs',
    latinName: 'Pulmones',
    system: 'respiratory',
    systemName: 'Respiratory System',
    category: 'organ',
    layer: 8,
    region: 'thorax',
    regionName: 'Pleural Cavities',
    description: 'Essential paired organs of respiration located in the thoracic cavity on either side of the mediastinum. The right lung has three lobes (superior, middle, inferior) and the left lung has two lobes with a cardiac notch.',
    function: 'Facilitates gas exchange by bringing ambient oxygen into contact with pulmonary alveolar capillaries and expelling carbon dioxide.',
    location: 'Occupies the left and right pleural cavities of the thorax, resting upon the convex diaphragm and bounded by the ribs.',
    relatedStructures: ['trachea', 'bronchi', 'heart', 'diaphragm', 'ribs'],
    bloodSupply: 'Pulmonary arteries (deoxygenated gas-exchange flow) and bronchial arteries from thoracic aorta (nutrient supply).',
    innervation: 'Pulmonary plexus (vagus nerve CN X and sympathetic thoracic trunks T2-T5).',
    histology: 'Consists of millions of alveoli lined by thin Type I pneumocytes (gas exchange) and surfactant-secreting Type II pneumocytes.',
    clinicalNotes: 'Site of pneumonia, asthma, chronic obstructive pulmonary disease (COPD), pulmonary embolism, and lung carcinomas.',
    funFact: 'If the total surface area of all alveoli in both adult lungs were spread out flat, it would cover an entire singles tennis court (approx. 70 square meters).',
    position3D: [0.0, 1.25, 0.15],
    scale3D: [0.95, 0.75, 0.45],
    color: '#f472b6',
    image: '/src/assets/images/realistic_lungs_anatomy_1790533441832.jpg'
  },
  trachea: {
    id: 'trachea',
    name: 'Trachea & Bronchi',
    latinName: 'Trachea et Arbus Bronchialis',
    system: 'respiratory',
    systemName: 'Respiratory System',
    category: 'organ',
    layer: 8,
    region: 'neck',
    regionName: 'Anterior Neck & Superior Mediastinum',
    description: 'Cartilaginous and membranous tube extending from the lower cricoid cartilage (C6) down to the carina (T4/T5), where it bifurcates into the right and left main bronchi.',
    function: 'Conducts warm, humidified, filtered air into the bronchial tree while preventing airway collapse during thoracic pressure changes.',
    location: 'Begins at C6 below the larynx, descends anterior to the esophagus in the midline of the neck and superior mediastinum.',
    relatedStructures: ['lungs', 'esophagus', 'thyroid_gland'],
    bloodSupply: 'Inferior thyroid arteries superiorly and bronchial arteries inferiorly.',
    innervation: 'Recurrent laryngeal nerves (branches of CN X vagus) and sympathetic branches.',
    histology: 'Pseudostratified ciliated columnar epithelium with goblet cells (mucociliary escalator) supported by 16-20 C-shaped hyaline cartilage rings.',
    clinicalNotes: 'Target for emergency tracheostomy and endotracheal intubation. Foreign body aspiration preferentially enters the wider, steeper right main bronchus.',
    funFact: 'C-shaped cartilage rings are incomplete posteriorly, allowing the adjacent esophagus to expand forward when swallowing food boluses.',
    position3D: [0.0, 1.65, 0.15],
    scale3D: [0.14, 0.45, 0.14],
    color: '#cbd5e1'
  },
  diaphragm: {
    id: 'diaphragm',
    name: 'Diaphragm',
    latinName: 'Diaphragma Thoracis',
    system: 'respiratory',
    systemName: 'Respiratory System',
    category: 'muscle',
    layer: 4,
    region: 'thorax',
    regionName: 'Thoracoabdominal Junction',
    description: 'A large, dome-shaped musculofibrous partition separating the thoracic cavity from the abdominal cavity, featuring a central tendon and three major apertures (caval, esophageal, aortic).',
    function: 'Primary muscle of respiration; its contraction flattens the dome, increasing thoracic vertical volume and generating negative intrathoracic pressure that draws air in.',
    location: 'Attached to xiphoid process, lower six costal cartilages, and lumbar vertebrae (crura); arches into left and right domes under the lungs and heart.',
    relatedStructures: ['lungs', 'heart', 'liver', 'stomach', 'esophagus'],
    bloodSupply: 'Superior and inferior phrenic arteries, musculophrenic, and pericardiophrenic arteries.',
    innervation: 'Entire motor supply from the Phrenic Nerves (C3, C4, C5: "C3, 4, 5 keeps the diaphragm alive").',
    histology: 'Skeletal muscle fibers radiating inward from peripheral bony attachments to a central aponeurotic tendon.',
    clinicalNotes: 'Phrenic nerve injury leads to hemidiaphragmatic paralysis. Herniation through the esophageal hiatus (hiatal hernia) causes acid reflux.',
    funFact: 'Hiccups (singultus) are involuntary spasmodic contractions of the diaphragm accompanied by sudden closure of the vocal cords.',
    position3D: [0.0, 0.88, 0.1],
    scale3D: [0.95, 0.18, 0.6],
    color: '#b91c1c'
  },

  // --- DIGESTIVE ---
  stomach: {
    id: 'stomach',
    name: 'Stomach',
    latinName: 'Gaster / Ventriculus',
    system: 'digestive',
    systemName: 'Digestive System',
    category: 'organ',
    layer: 8,
    region: 'abdomen',
    regionName: 'Left Hypochondrium & Epigastrium',
    description: 'A J-shaped muscular dilatation of the alimentary canal situated between the esophagus and the duodenum. Divided into cardia, fundus, body, and pyloric antrum.',
    function: 'Enzymatic and mechanical digestion of food through acidic gastric secretions (pepsin and hydrochloric acid) into a semi-liquid chyme.',
    location: 'Occupies the left upper quadrant, epigastric, and umbilical regions of the abdomen, tucked directly beneath the left hemidiaphragm.',
    relatedStructures: ['esophagus', 'liver', 'pancreas', 'spleen', 'small_intestine'],
    bloodSupply: 'Celiac trunk branches: left gastric, right gastric, right and left gastro-omental, and short gastric arteries.',
    innervation: 'Parasympathetic secretomotor input via anterior and posterior vagal trunks; sympathetic pain fibers via greater splanchnic nerves (T5-T9).',
    histology: 'Specialized simple columnar mucosa with deep gastric pits containing parietal cells (secreting HCl and intrinsic factor) and chief cells (pepsinogen).',
    clinicalNotes: 'Peptic ulcer disease associated with Helicobacter pylori or NSAID usage; gastric adenocarcinoma; gastroesophageal reflux disease (GERD).',
    funFact: 'The stomach produces a new protective mucus coating every two weeks; without it, stomach acid (pH 1.5-2.0, strong enough to dissolve zinc) would digest the organ itself.',
    position3D: [-0.15, 0.72, 0.22],
    scale3D: [0.45, 0.35, 0.35],
    color: '#f97316',
    image: '/src/assets/images/realistic_stomach_digestive_1790533455235.jpg'
  },
  liver: {
    id: 'liver',
    name: 'Liver',
    latinName: 'Hepar',
    system: 'digestive',
    systemName: 'Digestive System',
    category: 'organ',
    layer: 8,
    region: 'abdomen',
    regionName: 'Right Hypochondrium & Epigastrium',
    description: 'The largest internal metabolic gland in the body, reddish-brown in color, divided into a large right lobe, smaller left lobe, and smaller caudate and quadrate lobes.',
    function: 'Bile synthesis, detoxification of xenobiotics, carbohydrate glycogen storage, protein plasma synthesis (albumin, clotting factors), and lipid metabolism.',
    location: 'Right upper quadrant of abdominal cavity directly beneath the diaphragm, protected by the lower ribcage.',
    relatedStructures: ['gallbladder', 'stomach', 'pancreas', 'inferior_vena_cava', 'diaphragm'],
    bloodSupply: 'Dual blood supply: Hepatic Portal Vein (75%, nutrient-rich from intestines) and Hepatic Artery proper (25%, oxygenated from celiac trunk).',
    innervation: 'Hepatic plexus derived from celiac plexus and vagal branches.',
    histology: 'Hexagonal functional lobules with central veins, hepatocyte plates, sinusoidal fenestrated capillaries, and resident Kupffer macrophages.',
    clinicalNotes: 'Prone to hepatitis (viral/toxic), non-alcoholic fatty liver disease (NAFLD), cirrhosis with portal hypertension, and hepatocellular carcinoma.',
    funFact: 'The liver is the only visceral organ capable of true regeneration—even if up to 70% is surgically excised, it can regrow to full size within weeks.',
    position3D: [0.22, 0.78, 0.22],
    scale3D: [0.65, 0.38, 0.45],
    color: '#991b1b',
    image: '/src/assets/images/realistic_internal_organs_1790533390328.jpg'
  },
  pancreas: {
    id: 'pancreas',
    name: 'Pancreas',
    latinName: 'Pancreas',
    system: 'digestive',
    systemName: 'Digestive System',
    category: 'gland',
    layer: 8,
    region: 'abdomen',
    regionName: 'Retroperitoneum (Epigastrium)',
    description: 'An elongated, retroperitoneal gland lying transversely across the posterior abdominal wall. Features a head nestled in the C-loop of the duodenum, neck, body, and tail reaching the splenic hilum.',
    function: 'Dual endocrine function (Islets of Langerhans: insulin, glucagon, somatostatin) and exocrine function (acinar cells: lipase, amylase, trypsinogen for duodenal digestion).',
    location: 'Posterior to the stomach, extending from duodenal curvature horizontally across the spine to the spleen at the L1-L2 vertebral level.',
    relatedStructures: ['stomach', 'liver', 'gallbladder', 'spleen', 'small_intestine'],
    bloodSupply: 'Splenic artery and superior/inferior pancreaticoduodenal arteries.',
    innervation: 'Celiac and superior mesenteric plexuses (autonomic fibers).',
    histology: 'Exocrine serous acini with zymogen granules surrounding scattered pale endocrine Islets of Langerhans (beta, alpha, delta cells).',
    clinicalNotes: 'Type 1 and Type 2 diabetes mellitus; acute necrotizing pancreatitis; pancreatic ductal adenocarcinoma (notably aggressive presentation).',
    funFact: 'The pancreas produces about 1 to 1.5 liters of pancreatic juice every day containing bicarbonate that neutralizes caustic acidic chyme from the stomach.',
    position3D: [0.0, 0.62, 0.12],
    scale3D: [0.45, 0.14, 0.16],
    color: '#fbbf24'
  },
  small_intestine: {
    id: 'small_intestine',
    name: 'Small Intestine',
    latinName: 'Intestinum Tenue',
    system: 'digestive',
    systemName: 'Digestive System',
    category: 'organ',
    layer: 8,
    region: 'abdomen',
    regionName: 'Central Umbilical Region',
    description: 'A 6-meter convoluted muscular tube extending from the pyloric sphincter to the ileocecal valve, subdivided into duodenum (25cm), jejunum (2.5m), and ileum (3.5m).',
    function: 'Primary site of nutrient absorption, carbohydrate/fat/protein enzymatic hydrolysis, and immune barrier surveillance (Peyer patches).',
    location: 'Central abdominal cavity, surrounded on superior, lateral, and inferior margins by the large intestine.',
    relatedStructures: ['stomach', 'large_intestine', 'liver', 'pancreas'],
    bloodSupply: 'Superior mesenteric artery (SMA) via numerous jejunal and ileal arterial arcades; drained by superior mesenteric vein into portal vein.',
    innervation: 'Myenteric (Auerbach) and submucosal (Meissner) enteric nervous system plexuses; modulated by vagus and sympathetic splanchnic fibers.',
    histology: 'Mucosa with circular plicae, finger-like intestinal villi, and microvilli brush border, dramatically expanding absorptive surface area.',
    clinicalNotes: 'Celiac disease (gluten enteropathy), Crohn disease (frequently targeting terminal ileum), and small bowel obstruction due to adhesions.',
    funFact: 'Because of billions of microvilli forming the brush border, the absorptive surface area of the small intestine is approximately 30 square meters.',
    position3D: [0.0, 0.28, 0.2],
    scale3D: [0.65, 0.45, 0.35],
    color: '#f9a8d4'
  },
  large_intestine: {
    id: 'large_intestine',
    name: 'Large Intestine & Colon',
    latinName: 'Intestinum Crassum',
    system: 'digestive',
    systemName: 'Digestive System',
    category: 'organ',
    layer: 8,
    region: 'abdomen',
    regionName: 'Periphery of Abdomen & Pelvis',
    description: 'Extends from ileocecal junction to anus (approx 1.5m). Composed of cecum with vermiform appendix, ascending colon, transverse colon, descending colon, sigmoid colon, and rectum.',
    function: 'Absorption of water, electrolytes, and short-chain fatty acids; bacterial synthesis of Vitamin K; compaction and expulsion of fecal waste.',
    location: 'Frames the peripheral borders of the abdominal cavity like a picture frame, framing the coiled loops of the small intestine within.',
    relatedStructures: ['small_intestine', 'liver', 'stomach', 'urinary_bladder'],
    bloodSupply: 'Superior mesenteric artery (proximal two-thirds) and Inferior mesenteric artery (distal third); interconnected via the marginal artery of Drummond.',
    innervation: 'Vagus nerve (up to splenic flexure) and pelvic splanchnic nerves S2-S4 (distal third); intrinsic enteric nervous system.',
    histology: 'Characterized by absence of villi, abundant goblet cells for mucus lubrication, outer longitudinal muscle bundled into three taeniae coli.',
    clinicalNotes: 'Acute appendicitis; colorectal adenocarcinoma (frequent screening via colonoscopy); diverticulosis; ulcerative colitis.',
    funFact: 'The large intestine is host to over 100 trillion symbiotic microorganisms—outnumbering human cells in the body—known as the human gut microbiome.',
    position3D: [0.0, 0.38, 0.18],
    scale3D: [0.85, 0.65, 0.35],
    color: '#b45309'
  },

  // --- URINARY ---
  kidneys: {
    id: 'kidneys',
    name: 'Kidneys',
    latinName: 'Renes',
    system: 'urinary',
    systemName: 'Urinary System',
    category: 'organ',
    layer: 8,
    region: 'abdomen',
    regionName: 'Posterior Retroperitoneum (T12-L3)',
    description: 'Paired bean-shaped organs lying retroperitoneally against posterior abdominal wall muscles. Right kidney sits slightly lower than left due to the liver mass above.',
    function: 'Filtration of metabolic waste (urea, creatinine), blood pressure regulation (renin-angiotensin-aldosterone), erythropoietin secretion, and acid-base fluid homeostasis.',
    location: 'Retroperitoneal space on both sides of vertebral column between T12 and L3 vertebrae, embedded in perinephric adipose tissue.',
    relatedStructures: ['urinary_bladder', 'aorta', 'inferior_vena_cava', 'adrenal_glands'],
    bloodSupply: 'Renal arteries arising directly from abdominal aorta at L1-L2; receive 20-25% of total resting cardiac output.',
    innervation: 'Renal plexus (sympathetic vasoconstrictor fibers from T10-L1 splanchnic nerves).',
    histology: 'Outer renal cortex containing ~1 million nephrons (glomerular Bowman capsules) and inner renal medulla containing renal pyramids and collecting ducts.',
    clinicalNotes: 'Chronic kidney disease, nephrolithiasis (kidney stones causing renal colic), glomerulonephritis, and renal cell carcinoma.',
    funFact: 'Both kidneys filter around 180 liters (48 gallons) of fluid daily, but tubular reabsorption reclaims over 99%, producing roughly 1.5 liters of urine.',
    position3D: [0.0, 0.68, -0.05],
    scale3D: [0.75, 0.32, 0.2],
    color: '#831843'
  },
  urinary_bladder: {
    id: 'urinary_bladder',
    name: 'Urinary Bladder',
    latinName: 'Vesica Urinaria',
    system: 'urinary',
    systemName: 'Urinary System',
    category: 'organ',
    layer: 8,
    region: 'pelvis',
    regionName: 'True Pelvic Cavity',
    description: 'A distensible hollow muscular reservoir in the pelvic cavity directly posterior to the pubic symphysis. Features a trigone bounded by two ureteric orifices and the urethral internal orifice.',
    function: 'Temporarily collects and stores urine delivered continuously from kidneys via ureters, then evacuates urine voluntarily during micturition.',
    location: 'Resting on the pelvic floor behind the pubic bone; expands superiorly into the abdominal cavity when filled with urine.',
    relatedStructures: ['kidneys', 'pelvis_sacrum', 'prostate_uterus'],
    bloodSupply: 'Superior and inferior vesical arteries arising from the internal iliac artery.',
    innervation: 'Parasympathetic fibers via pelvic splanchnic nerves (S2-S4, contracts detrusor muscle for voiding); sympathetic via hypogastric plexus (continence).',
    histology: 'Specialized stratified transitional epithelium (urothelium) with umbrella cells capable of stretching, supported by thick interlacing detrusor smooth muscle.',
    clinicalNotes: 'Urinary tract infections (cystitis), bladder calculi, urinary incontinence, and urothelial (transitional cell) carcinoma.',
    funFact: 'When empty, the bladder folds flat behind the pubic bone; when fully distended, it can hold up to 500-700 mL of urine and rise above the belly button.',
    position3D: [0.0, -0.08, 0.16],
    scale3D: [0.32, 0.28, 0.26],
    color: '#facc15'
  },

  // --- NERVOUS ---
  brain: {
    id: 'brain',
    name: 'Brain',
    latinName: 'Encephalon',
    system: 'nervous',
    systemName: 'Nervous System',
    category: 'organ',
    layer: 6,
    region: 'head',
    regionName: 'Cranial Cavity',
    description: 'The master organ of the human central nervous system encased within the neurocranium. Comprises the cerebrum (two hemispheres), cerebellum, and brainstem (midbrain, pons, medulla oblongata).',
    function: 'Integrates sensory information, controls voluntary motor execution, regulates autonomic homeostasis (breathing, heart rate), houses cognition, speech, memory, and consciousness.',
    location: 'Enclosed within the cranial cavity of the skull, bathed in cerebrospinal fluid (CSF) inside three meningeal layers (dura, arachnoid, pia mater).',
    relatedStructures: ['cranium_skull', 'spinal_cord', 'cranial_nerves'],
    bloodSupply: 'Circle of Willis formed by the paired internal carotid arteries and basilar artery (from vertebral arteries); drained by dural venous sinuses.',
    innervation: 'Gives rise to 12 pairs of cranial nerves (CN I through XII).',
    histology: 'Outer gray matter cortex containing billions of neuronal cell bodies and unmyelinated dendrites; inner white matter containing myelinated axonal tracts and glial cells.',
    clinicalNotes: 'Ischemic and hemorrhagic stroke; traumatic brain injury (concussion); neurodegenerative diseases (Alzheimer, Parkinson); glioblastoma.',
    funFact: 'Although the human brain accounts for only about 2% of total body weight, it consumes more than 20% of the body’s total oxygen and glucose supply.',
    position3D: [0.0, 2.35, 0.05],
    scale3D: [0.42, 0.42, 0.48],
    color: '#c084fc',
    image: '/src/assets/images/realistic_brain_anatomy_1790533427833.jpg'
  },
  spinal_cord: {
    id: 'spinal_cord',
    name: 'Spinal Cord',
    latinName: 'Medulla Spinalis',
    system: 'nervous',
    systemName: 'Nervous System',
    category: 'nerve',
    layer: 6,
    region: 'spine',
    regionName: 'Vertebral Canal',
    description: 'A cylindrical bundle of nervous tissue extending from the medulla oblongata at the foramen magnum down to the conus medullaris (L1-L2 level in adults), giving off 31 pairs of spinal nerves.',
    function: 'Transmission of ascending sensory signals to the brain, descending motor commands to muscles, and orchestration of autonomic and spinal reflexes.',
    location: 'Runs within the vertebral canal formed by successive vertebral foramina from the skull base to the upper lumbar spine.',
    relatedStructures: ['brain', 'vertebral_column', 'sciatic_nerve', 'brachial_plexus'],
    bloodSupply: 'Single anterior spinal artery and paired posterior spinal arteries, reinforced by segmental radicular arteries (e.g. Artery of Adamkiewicz).',
    innervation: '31 spinal nerve pairs: 8 cervical, 12 thoracic, 5 lumbar, 5 sacral, 1 coccygeal.',
    histology: 'Central H-shaped butterfly of gray matter (anterior, posterior, and lateral horns) surrounded by peripheral white matter tracts (dorsal, lateral, anterior columns).',
    clinicalNotes: 'Spinal cord injury (paraplegia, tetraplegia); herniated intervertebral disc with radiculopathy; multiple sclerosis demyelinating lesions.',
    funFact: 'The spinal cord stops growing in length around age 4, while the vertebral column continues growing; hence in adults, the spinal cord ends around vertebra L1-L2.',
    position3D: [0.0, 1.45, -0.06],
    scale3D: [0.08, 1.6, 0.08],
    color: '#e9d5ff'
  },
  sciatic_nerve: {
    id: 'sciatic_nerve',
    name: 'Sciatic Nerve & Plexus',
    latinName: 'Nervus Ischiadicus',
    system: 'nervous',
    systemName: 'Nervous System',
    category: 'nerve',
    layer: 6,
    region: 'lower_limb',
    regionName: 'Gluteal Region & Posterior Thigh',
    description: 'The largest and longest nerve in the human body, formed from the ventral rami of spinal nerves L4 through S3 of the sacral plexus. Descends through the greater sciatic foramen into the posterior thigh.',
    function: 'Motor innervation to hamstring muscles and all muscles of the lower leg and foot; sensory innervation to skin of lateral leg and entire foot.',
    location: 'Exits pelvis inferior to piriformis muscle, passes midway between ischial tuberosity and greater trochanter, descends down posterior thigh.',
    relatedStructures: ['spinal_cord', 'pelvis_sacrum', 'femur_bone'],
    bloodSupply: 'Arteria comitans nervi ischiadici (branch of inferior gluteal artery).',
    innervation: 'Arises from ventral rami of L4, L5, S1, S2, S3 spinal nerves.',
    histology: 'Heavy connective tissue epineurium enclosing multiple nerve fascicles wrapped in protective perineurium.',
    clinicalNotes: 'Sciatica (sharp radiating radicular leg pain from lumbar disc herniation); piriformis syndrome entrapment; risk of iatrogenic injury during intramuscular gluteal injections.',
    funFact: 'The sciatic nerve can reach the thickness of an adult human thumb at its widest point in the upper posterior thigh.',
    position3D: [-0.22, -0.7, -0.05],
    scale3D: [0.1, 1.2, 0.1],
    color: '#facc15'
  },

  // --- SKELETAL ---
  cranium_skull: {
    id: 'cranium_skull',
    name: 'Skull & Cranium',
    latinName: 'Cranium Humanum',
    system: 'skeletal',
    systemName: 'Skeletal System',
    category: 'bone',
    layer: 5,
    region: 'head',
    regionName: 'Cephalic Skeleton',
    description: 'The complex bony framework composed of 22 bones: 8 neurocranial bones (frontal, parietal, occipital, temporal, sphenoid, ethmoid) safeguarding the brain and 14 viscerocranial facial bones.',
    function: 'Protects the delicate brain, cranial meninges, and special sensory organs (eyes, ears, olfaction); provides mechanical anchor for mastication and facial expression muscles.',
    location: 'Superior pole of the axial skeleton, articulating with the first cervical vertebra (atlas C1) at the atlanto-occipital joint.',
    relatedStructures: ['brain', 'mandible', 'vertebral_column'],
    bloodSupply: 'Middle meningeal artery and external/internal carotid branches.',
    innervation: 'Sensory innervation of pericranium via branches of trigeminal nerve (CN V).',
    histology: 'Flat bones featuring dense inner and outer compact cortical plates sandwiching vascularized diploë cancellous trabecular bone.',
    clinicalNotes: 'Skull fractures (linear, depressed, basilar with CSF rhinorrhea/otorrhea); temporomandibular joint (TMJ) arthropathy; craniosynostosis in infants.',
    funFact: 'Infant skulls have membranous fibrous gaps called fontanelles ("soft spots") that allow the head to compress safely during birth and permit rapid brain growth.',
    position3D: [0.0, 2.35, 0.08],
    scale3D: [0.55, 0.58, 0.6],
    color: '#f1f5f9',
    image: '/src/assets/images/realistic_bone_isolated_1790533483130.jpg'
  },
  vertebral_column: {
    id: 'vertebral_column',
    name: 'Vertebral Column (Spine)',
    latinName: 'Columna Vertebralis',
    system: 'skeletal',
    systemName: 'Skeletal System',
    category: 'bone',
    layer: 5,
    region: 'spine',
    regionName: 'Axial Spine',
    description: 'Flexible bony column consisting of 33 vertebrae: 7 cervical, 12 thoracic, 5 lumbar, 5 fused sacral, and 4 fused coccygeal, separated by fibrocartilaginous intervertebral discs.',
    function: 'Supports body weight, provides axial structural stiffness and mobility, and shields the delicate spinal cord and spinal nerve roots within its canal.',
    location: 'Forms the central dorsal axis of the body from the base of the skull (foramen magnum) down to the pelvic coccyx.',
    relatedStructures: ['spinal_cord', 'ribs', 'pelvis_sacrum', 'cranium_skull'],
    bloodSupply: 'Segmental spinal arteries (vertebral, posterior intercostal, lumbar, and lateral sacral arteries).',
    innervation: 'Meningeal (sinuvertebral) recurrent nerves innervate periosteum, posterior longitudinal ligament, and outer annulus fibrosus.',
    histology: 'Cylindrical cancellous vertebral bodies surrounded by dense cortical bone; intervertebral discs have a gelatinous nucleus pulposus inside a tough fibrocartilaginous annulus fibrosus.',
    clinicalNotes: 'Herniated intervertebral disc; spinal canal stenosis; scoliosis, kyphosis; osteoporotic vertebral wedge compression fractures.',
    funFact: 'Because gravity compresses the hydrated intervertebral discs throughout the day, you are about 1 to 2 centimeters taller when you wake up in the morning than when you go to bed.',
    position3D: [0.0, 1.35, -0.1],
    scale3D: [0.25, 1.8, 0.22],
    color: '#e2e8f0'
  },
  ribs: {
    id: 'ribs',
    name: 'Rib Cage & Sternum',
    latinName: 'Thorax et Sternum',
    system: 'skeletal',
    systemName: 'Skeletal System',
    category: 'bone',
    layer: 5,
    region: 'thorax',
    regionName: 'Thoracic Cage',
    description: 'An elastic osteocartilaginous cage formed by 12 pairs of curved ribs, anterior costal cartilages, the midline sternum (manubrium, body, xiphoid process), and 12 thoracic vertebrae.',
    function: 'Safeguards the heart, lungs, and great thoracic vessels, while flexing cyclically via intercostal muscles to drive pulmonary ventilation.',
    location: 'Encloses the thoracic cavity from the superior thoracic aperture down to the inferior thoracic diaphragm boundary.',
    relatedStructures: ['heart', 'lungs', 'vertebral_column', 'pectoralis_muscle'],
    bloodSupply: 'Anterior and posterior intercostal arteries and internal thoracic arteries.',
    innervation: 'Intercostal nerves (ventral rami of T1-T11 thoracic spinal nerves).',
    histology: 'Curved trabecular bone containing hematopoietic red bone marrow enclosed within a dense outer periosteal cortical sheath.',
    clinicalNotes: 'Rib fractures (risk of flail chest, pneumothorax, hemothorax); costochondritis (Tietze syndrome); sternal fractures from steering wheel impact.',
    funFact: 'Ribs 1-7 are "true ribs" attaching directly to the sternum; 8-10 are "false ribs" attaching via cartilage; 11-12 are "floating ribs" with no anterior attachment at all.',
    position3D: [0.0, 1.25, 0.12],
    scale3D: [0.92, 0.95, 0.55],
    color: '#f8fafc',
    image: '/src/assets/images/realistic_human_skeleton_1790533375558.jpg'
  },
  pelvis_sacrum: {
    id: 'pelvis_sacrum',
    name: 'Pelvis & Sacrum',
    latinName: 'Pelvis et Os Sacrum',
    system: 'skeletal',
    systemName: 'Skeletal System',
    category: 'bone',
    layer: 5,
    region: 'pelvis',
    regionName: 'Pelvic Girdle',
    description: 'A heavy, basin-shaped ring of bones connecting the axial vertebral column to the lower limbs, formed by the paired hip bones (ilium, ischium, pubis) and the wedge-shaped posterior sacrum.',
    function: 'Transfers upper body weight to the femurs during stance and locomotion, supports pelvic organs, and provides broad anchor sites for locomotion muscles.',
    location: 'Inferior termination of the torso, articulating with L5 vertebra superiorly and femoral heads at the deep acetabular ball-and-socket joints.',
    relatedStructures: ['femur_bone', 'vertebral_column', 'urinary_bladder', 'sciatic_nerve'],
    bloodSupply: 'Internal and external iliac arteries and lateral sacral branches.',
    innervation: 'Sacral plexus (L4-S4) giving rise to major peripheral nerves.',
    histology: 'Thick cortical bone with high tensile strength sandwiching trabecular stress arches adapted to high gravitational mechanical loads.',
    clinicalNotes: 'High-energy pelvic fractures with catastrophic life-threatening retroperitoneal bleeding; sacroiliitis; pubic symphysis separation during childbirth.',
    funFact: 'The female pelvis is significantly wider, lighter, and possesses a much rounder pelvic inlet with a subpubic angle >80° (compared to <70° in males) to facilitate childbirth.',
    position3D: [0.0, 0.05, 0.02],
    scale3D: [0.85, 0.45, 0.45],
    color: '#e2e8f0'
  },
  femur_bone: {
    id: 'femur_bone',
    name: 'Femur (Thigh Bone)',
    latinName: 'Os Femoris',
    system: 'skeletal',
    systemName: 'Skeletal System',
    category: 'bone',
    layer: 5,
    region: 'lower_limb',
    regionName: 'Thigh (Femoral Region)',
    description: 'The longest, heaviest, and strongest long bone in the human body. Features a spherical head, neck (angle of inclination ~125°), greater and lesser trochanters, shaft, and lateral/medial condyles.',
    function: 'Transmits body weight from hip bone to tibia, serving as the primary biomechanical lever for walking, running, and jumping.',
    location: 'Extends obliquely from the acetabulum of the pelvis down to the knee joint, converging toward the midline at the patella.',
    relatedStructures: ['pelvis_sacrum', 'quadriceps_muscle', 'tibia_fibula', 'patella'],
    bloodSupply: 'Medial and lateral circumflex femoral arteries (supplying the femoral head/neck) and deep femoral (profunda femoris) perforating branches.',
    innervation: 'Periosteum innervated by branches from the femoral, obturator, and sciatic nerves.',
    histology: 'Extremely dense, thick cortical cylindrical diaphysis surrounding a central medullary canal containing fatty yellow bone marrow.',
    clinicalNotes: 'Femoral neck fractures in elderly osteoporotic patients carry high risk of avascular necrosis (AVN); high-energy midshaft femoral fractures can cause shock.',
    funFact: 'The human femur is strong enough to resist up to 30 times an adult’s body weight—making it pound-for-pound stronger than solid reinforced concrete.',
    position3D: [-0.26, -0.65, 0.02],
    scale3D: [0.22, 1.15, 0.22],
    color: '#f1f5f9'
  },
  tibia_fibula: {
    id: 'tibia_fibula',
    name: 'Tibia & Fibula (Leg Bones)',
    latinName: 'Tibia et Fibula',
    system: 'skeletal',
    systemName: 'Skeletal System',
    category: 'bone',
    layer: 5,
    region: 'lower_limb',
    regionName: 'Crus (Lower Leg)',
    description: 'The two bones of the lower leg: the medial tibia is the thick weight-bearing shin bone; the slender lateral fibula serves primarily for muscle attachment and stabilizes the ankle mortise.',
    function: 'Transmits ground reaction forces and body weight from the knee joint to the ankle talus; anchors lower leg compartmental muscles.',
    location: 'Spans from knee joint down to the ankle, terminating distally as the medial malleolus (tibia) and lateral malleolus (fibula).',
    relatedStructures: ['femur_bone', 'patella', 'gastrocnemius_muscle'],
    bloodSupply: 'Anterior and posterior tibial arteries and peroneal (fibular) artery.',
    innervation: 'Deep peroneal, superficial peroneal, and tibial nerves.',
    histology: 'Triangular cross-section long bones with robust cortical walls connected by a fibrous syndesmotic interosseous membrane.',
    clinicalNotes: 'Tibial plateau fractures; "shin splints" (medial tibial stress syndrome); open compound tibial fractures due to subcutaneous anterior border.',
    funFact: 'The anterior crest of your tibia has almost no muscle or subcutaneous fat covering it, which is why even minor bumps to the shin hurt so acutely!',
    position3D: [-0.24, -1.65, 0.0],
    scale3D: [0.18, 0.95, 0.18],
    color: '#e2e8f0'
  },

  // --- MUSCULAR ---
  pectoralis_muscle: {
    id: 'pectoralis_muscle',
    name: 'Pectoralis Major',
    latinName: 'Musculus Pectoralis Major',
    system: 'muscular',
    systemName: 'Muscular System',
    category: 'muscle',
    layer: 3,
    region: 'thorax',
    regionName: 'Anterior Chest Wall',
    description: 'Thick, fan-shaped muscle situated on the anterior chest wall. Consists of a clavicular head arising from the medial clavicle and a sternocostal head from the sternum and upper costal cartilages.',
    function: 'Adduction, internal (medial) rotation, and forward flexion of the humerus at the glenohumeral shoulder joint (essential in pushing and hugging motions).',
    location: 'Covers the upper anterior ribcage, inserting into the lateral lip of the intertubercular bicipital sulcus of the humerus.',
    relatedStructures: ['ribs', 'deltoid_muscle', 'lungs'],
    bloodSupply: 'Pectoral branch of the thoracoacromial artery and lateral thoracic artery.',
    innervation: 'Medial and lateral pectoral nerves originating from the brachial plexus (C5-T1).',
    histology: 'Parallel bundles of multinucleated striated myofibers rich in fast-twitch Type II fibers capable of generating high rapid force.',
    clinicalNotes: 'Pectoralis tendon ruptures during heavy bench pressing; Poland syndrome (congenital unilateral absence of pectoralis major).',
    funFact: 'Bodybuilders and sprinters train the pectoralis major for maximum force output—it is one of the most powerful adductors in the upper extremity.',
    position3D: [0.0, 1.45, 0.28],
    scale3D: [0.85, 0.35, 0.18],
    color: '#dc2626',
    image: '/src/assets/images/realistic_muscle_isolated_1790533469797.jpg'
  },
  deltoid_muscle: {
    id: 'deltoid_muscle',
    name: 'Deltoid Muscle',
    latinName: 'Musculus Deltoideus',
    system: 'muscular',
    systemName: 'Muscular System',
    category: 'muscle',
    layer: 3,
    region: 'upper_limb',
    regionName: 'Shoulder Cap',
    description: 'Large triangular muscle covering the glenohumeral joint, giving the rounded contour to the shoulder. Subdivided into anterior, lateral (multipennate), and posterior fibers.',
    function: 'Major abductor of the arm past 15 degrees (lateral fibers); anterior fibers flex and medially rotate; posterior fibers extend and laterally rotate the arm.',
    location: 'Originates from lateral clavicle, acromion, and spine of the scapula; converges to insert onto the deltoid tuberosity on the mid-lateral humerus.',
    relatedStructures: ['pectoralis_muscle', 'biceps_brachii', 'humerus_bone'],
    bloodSupply: 'Posterior circumflex humeral artery and deltoid branch of thoracoacromial artery.',
    innervation: 'Axillary nerve (C5, C6) winding around surgical neck of humerus.',
    histology: 'Multipennate architecture in its central lateral component, packing maximum physiological cross-sectional area for lifting power.',
    clinicalNotes: 'Preferred site for intramuscular vaccinations; susceptible to axillary nerve injury during anterior shoulder dislocation or surgical neck fractures.',
    funFact: 'The multipennate arrangement of the middle deltoid allows it to exert tremendous lifting leverage despite having a relatively short length of muscle fiber.',
    position3D: [-0.55, 1.55, 0.12],
    scale3D: [0.28, 0.32, 0.28],
    color: '#b91c1c'
  },
  biceps_brachii: {
    id: 'biceps_brachii',
    name: 'Biceps Brachii',
    latinName: 'Musculus Biceps Brachii',
    system: 'muscular',
    systemName: 'Muscular System',
    category: 'muscle',
    layer: 3,
    region: 'upper_limb',
    regionName: 'Anterior Arm (Brachium)',
    description: 'Prominent two-headed muscle on the anterior compartment of the arm. The long head arises from the supraglenoid tubercle of the scapula, while the short head arises from the coracoid process.',
    function: 'Powerful supinator of the flexed forearm and prime flexor of the elbow joint; also assists in weak shoulder flexion.',
    location: 'Anterior compartment of the arm, inserting onto the radial tuberosity and bicipital aponeurosis into deep forearm fascia.',
    relatedStructures: ['deltoid_muscle', 'triceps_brachii', 'brachial_artery'],
    bloodSupply: 'Muscular branches of the brachial artery.',
    innervation: 'Musculocutaneous nerve (C5, C6).',
    histology: 'Fusiform striated skeletal muscle fibers operating over two joints (biarticular muscle).',
    clinicalNotes: 'Proximal long head tendon rupture causes a retracted distal muscle bulge famously known as the "Popeye deformity".',
    funFact: 'The biceps is actually a much more powerful supinator (turning your palm upward, like driving a corkscrew) than it is an elbow flexor!',
    position3D: [-0.58, 1.25, 0.12],
    scale3D: [0.18, 0.45, 0.18],
    color: '#dc2626'
  },
  rectus_abdominis: {
    id: 'rectus_abdominis',
    name: 'Rectus Abdominis ("Six-Pack")',
    latinName: 'Musculus Rectus Abdominis',
    system: 'muscular',
    systemName: 'Muscular System',
    category: 'muscle',
    layer: 3,
    region: 'abdomen',
    regionName: 'Anterior Abdominal Wall',
    description: 'Long paired strap-like muscle running vertically on each side of the anterior abdominal midline (linea alba), segmented by 3-4 transverse fibrous tendinous intersections.',
    function: 'Flexes the lumbar vertebral column (bringing thorax toward pelvis), compresses abdominal viscera, and assists in forced exhalation and intra-abdominal pressure generation.',
    location: 'Enclosed in the fibrous rectus sheath, extending from the pubic crest below to the 5th-7th costal cartilages and xiphoid process above.',
    relatedStructures: ['small_intestine', 'large_intestine', 'pelvis_sacrum'],
    bloodSupply: 'Superior epigastric artery (from internal thoracic) and inferior epigastric artery (from external iliac).',
    innervation: 'Thoracoabdominal intercostal nerves (ventral rami T7-T11) and subcostal nerve (T12).',
    histology: 'Multi-segmented parallel skeletal muscle fibers anchored securely by dense collagenous aponeurotic sheaths.',
    clinicalNotes: 'Diastasis recti (widening of linea alba post-pregnancy or obesity); rectus sheath hematoma from rupture of inferior epigastric vessels.',
    funFact: 'The distinct "six-pack" or "eight-pack" appearance is formed by rigid transverse connective tissue bands called tendinous intersections adhering to the anterior sheath.',
    position3D: [0.0, 0.55, 0.22],
    scale3D: [0.45, 0.65, 0.12],
    color: '#b91c1c'
  },
  quadriceps_muscle: {
    id: 'quadriceps_muscle',
    name: 'Quadriceps Femoris',
    latinName: 'Musculus Quadriceps Femoris',
    system: 'muscular',
    systemName: 'Muscular System',
    category: 'muscle',
    layer: 3,
    region: 'lower_limb',
    regionName: 'Anterior Thigh',
    description: 'Massive four-part muscle group on the front of the thigh composed of rectus femoris, vastus lateralis, vastus medialis, and vastus intermedius, converging into the patellar tendon.',
    function: 'The sole prime extensor of the knee joint; rectus femoris also assists in hip flexion. Essential for walking, running, standing up, and stair climbing.',
    location: 'Occupies the entire anterior and lateral compartment of the thigh, inserting via the patella and patellar ligament into the tibial tuberosity.',
    relatedStructures: ['femur_bone', 'patella', 'tibia_fibula', 'gastrocnemius_muscle'],
    bloodSupply: 'Lateral circumflex femoral artery and deep femoral (profunda femoris) branches.',
    innervation: 'Femoral nerve (L2, L3, L4).',
    histology: 'Pennate and bipennate arrangements capable of generating some of the highest contractile forces in the human musculoskeletal system.',
    clinicalNotes: 'Quadriceps tendon rupture, patellar tendinitis ("jumper\'s knee"), and patellofemoral pain syndrome due to vastus medialis obliquus (VMO) weakness.',
    funFact: 'Your quadriceps muscle group can produce upwards of 1,000 pounds of force when you push off the ground during a powerful sprint or vertical leap.',
    position3D: [-0.26, -0.65, 0.12],
    scale3D: [0.26, 0.95, 0.26],
    color: '#b91c1c'
  },
  gastrocnemius_muscle: {
    id: 'gastrocnemius_muscle',
    name: 'Gastrocnemius & Soleus (Calf)',
    latinName: 'Musculus Gastrocnemius et Soleus',
    system: 'muscular',
    systemName: 'Muscular System',
    category: 'muscle',
    layer: 3,
    region: 'lower_limb',
    regionName: 'Posterior Leg (Suras)',
    description: 'The triceps surae muscle complex forming the visible muscular bulge of the calf. The two-headed gastrocnemius lies superficially over the deeper postural soleus muscle.',
    function: 'Powerful plantarflexion of the foot at the ankle joint (propelling the body forward during walking and running) and knee flexion assistance.',
    location: 'Posterior compartment of the lower leg, fusing distally into the massive calcaneal (Achilles) tendon attaching to the posterior calcaneus.',
    relatedStructures: ['tibia_fibula', 'quadriceps_muscle', 'sciatic_nerve'],
    bloodSupply: 'Sural branches of the popliteal artery and posterior tibial artery.',
    innervation: 'Tibial nerve (S1, S2).',
    histology: 'Gastrocnemius is rich in fast-twitch fibers for sprinting; the underlying soleus consists primarily of slow-twitch fatigue-resistant fibers for standing posture.',
    clinicalNotes: 'Achilles tendon rupture (sudden loud pop with positive Thompson test); deep vein thrombosis (DVT) in soleal venous sinuses; calf strain ("tennis leg").',
    funFact: 'The Achilles tendon is the thickest and strongest tendon in the human body, bearing loads up to 10 times body weight during running and jumping.',
    position3D: [-0.24, -1.55, -0.06],
    scale3D: [0.2, 0.7, 0.2],
    color: '#991b1b'
  },

  // --- ENDOCRINE ---
  thyroid_gland: {
    id: 'thyroid_gland',
    name: 'Thyroid Gland',
    latinName: 'Glandula Thyroidea',
    system: 'endocrine',
    systemName: 'Endocrine System',
    category: 'gland',
    layer: 8,
    region: 'neck',
    regionName: 'Anterior Neck',
    description: 'A butterfly-shaped endocrine gland consisting of right and left lobes connected across the midline by a central isthmus overlying the 2nd to 4th tracheal rings.',
    function: 'Produces thyroid hormones (thyroxine T4, triiodothyronine T3) that control basal metabolic rate and calcitonin for calcium regulation.',
    location: 'Low in the anterior neck, hugging the cricoid cartilage and upper trachea anteriorly.',
    relatedStructures: ['trachea', 'carotid_artery', 'larynx'],
    bloodSupply: 'Superior thyroid artery (from external carotid) and inferior thyroid artery (from thyrocervical trunk). Extremely rich vascular supply.',
    innervation: 'Cervical sympathetic ganglia and branches from recurrent laryngeal nerves.',
    histology: 'Thyroid follicles filled with gelatinous colloid (thyroglobulin) surrounded by single-layer follicular cells and parafollicular C-cells.',
    clinicalNotes: 'Hypothyroidism (Hashimoto thyroiditis, lethargy, cold intolerance); Hyperthyroidism (Graves disease, goiter, exophthalmos); thyroid nodules.',
    funFact: 'The thyroid has one of the highest blood flow rates per gram of tissue of any organ in the body—exceeded only by the adrenal glands and kidneys.',
    position3D: [0.0, 1.82, 0.16],
    scale3D: [0.22, 0.14, 0.12],
    color: '#ec4899'
  },
  adrenal_glands: {
    id: 'adrenal_glands',
    name: 'Adrenal (Suprarenal) Glands',
    latinName: 'Glandulae Suprarenales',
    system: 'endocrine',
    systemName: 'Endocrine System',
    category: 'gland',
    layer: 8,
    region: 'abdomen',
    regionName: 'Retroperitoneal Upper Abdomen',
    description: 'Paired pyramid-shaped endocrine glands perched like triangular caps on the superior poles of both kidneys, surrounded by renal fascia.',
    function: 'Adrenal cortex synthesizes steroid hormones (aldosterone, cortisol, androgens); adrenal medulla secretes catecholamines (epinephrine, norepinephrine).',
    location: 'Directly atop the superior medial aspect of both kidneys in the retroperitoneum at the T12 level.',
    relatedStructures: ['kidneys', 'inferior_vena_cava', 'aorta'],
    bloodSupply: 'Superior, middle, and inferior suprarenal arteries (rich triple arterial source).',
    innervation: 'Direct preganglionic sympathetic fibers from greater splanchnic nerve to the adrenal medulla (functioning as a specialized sympathetic ganglion).',
    histology: 'Three cortical zones (Zona glomerulosa: mineralocorticoids; Zona fasciculata: glucocorticoids; Zona reticularis: androgens) plus inner chromaffin medulla.',
    clinicalNotes: 'Cushing syndrome (excess cortisol); Addison disease (adrenocortical insufficiency); Pheochromocytoma (catecholamine-secreting tumor causing hypertensive crises).',
    funFact: 'During acute "fight-or-flight" stress, the adrenal medulla fires epinephrine directly into the bloodstream within milliseconds, instantly dilating airways and surging heart rate.',
    position3D: [0.0, 0.88, -0.05],
    scale3D: [0.65, 0.12, 0.14],
    color: '#f59e0b'
  },

  // --- LYMPHATIC ---
  spleen: {
    id: 'spleen',
    name: 'Spleen',
    latinName: 'Lien / Splen',
    system: 'lymphatic',
    systemName: 'Lymphatic & Immune System',
    category: 'organ',
    layer: 8,
    region: 'abdomen',
    regionName: 'Left Hypochondrium',
    description: 'The largest secondary lymphoid organ in the human body, oval and purplish in color, resting in the left upper quadrant under ribs 9 through 11.',
    function: 'Filters circulating blood, destroys senescent red blood cells and platelets, recycles iron, and mounts primary adaptive humoral immune responses.',
    location: 'Posterior part of the left hypochondrium, between the gastric fundus and the left hemidiaphragm, protected by the 9th to 11th ribs.',
    relatedStructures: ['stomach', 'pancreas', 'kidneys', 'diaphragm'],
    bloodSupply: 'Splenic artery (tortuous branch from celiac trunk); drained by splenic vein into hepatic portal vein.',
    innervation: 'Celiac plexus sympathetic fibers.',
    histology: 'Consists of Red Pulp (venous sinusoids and splenic cords filtering RBCs) and White Pulp (periarteriolar lymphoid sheaths PALS and follicles containing T and B lymphocytes).',
    clinicalNotes: 'Splenomegaly (in mononucleosis, malaria, portal hypertension); splenic rupture from blunt left rib trauma causes massive hemoperitoneum.',
    funFact: 'The spleen holds a reserve of red blood cells and platelets that can be squeezed into circulation during emergency hemorrhagic shock.',
    position3D: [-0.38, 0.74, 0.08],
    scale3D: [0.24, 0.32, 0.18],
    color: '#701a75'
  }
};

export const ANATOMY_LIST: AnatomicalStructure[] = Object.values(ANATOMY_STRUCTURES);

export function getStructuresBySystem(systemId: string): AnatomicalStructure[] {
  if (systemId === 'all') return ANATOMY_LIST;
  return ANATOMY_LIST.filter(s => s.system === systemId);
}

export function getStructuresByLayer(layerNum: number): AnatomicalStructure[] {
  return ANATOMY_LIST.filter(s => s.layer <= layerNum);
}
